const sequelize = require('./sequelize.js');
const { NBATeams, Player } = require('./NBATeam.js');

const teamData = {
'Brooklyn Nets': [
  { playerName: 'Pascal Siakam', position: 'PF', overall: 89 },
  { playerName: 'Ivica Zubac', position: 'C', overall: 88 },
  { playerName: 'RJ Barrett', position: 'SG', overall: 82 },
  { playerName: 'Dillon Brooks', position: 'SF', overall: 81 },
  { playerName: 'TJ McConnell', position: 'PG', overall: 80 },
  { playerName: 'Fred VanVleet', position: 'PG', overall: 80 },
  { playerName: 'Jonas Valanciunas', position: 'C', overall: 79 },
  { playerName: 'Jarred Vanderbilt', position: 'PF', overall: 78 },
  { playerName: 'Jordan Clarkson', position: 'SG', overall: 77 },
  { playerName: 'Furkan Da Silva', position: 'SF', overall: 76 }, 
  { playerName: 'Jose Alvarado', position: 'PG', overall: 75 },
  { playerName: 'Josh Okogie', position: 'SG', overall: 75 },
  { playerName: 'Caleb Martin', position: 'SF', overall: 74 },
  { playerName: 'DeAndre Jordan', position: 'C', overall: 74 },
],
'Denver Nuggets': [
  { playerName: 'Jaylen Brown', position: 'SF', overall: 91 },
  { playerName: 'Tyrese Maxey', position: 'PG', overall: 89 },
  { playerName: 'Mikal Bridges', position: 'SG', overall: 84 },
  { playerName: 'Isaiah Hartenstein', position: 'C', overall: 83 },
  { playerName: 'Keyonte George', position: 'PG', overall: 82 },
  { playerName: 'Kris Murray', position: 'SF', overall: 81 },
  { playerName: 'Jared McCain', position: 'PG', overall: 80 },
  { playerName: 'Neemias Queta', position: 'C', overall: 76 },
  { playerName: 'Patrick Williams', position: 'PF', overall: 76 },
  { playerName: 'KJ Williams', position: 'PF', overall: 76 },
  { playerName: 'Torrey Craig', position: 'PF', overall: 75 },
  { playerName: 'Brandon Boston Jr.', position: 'SG', overall: 74 },
  { playerName: 'Quinten Post', position: 'C', overall: 74 },
  { playerName: 'Landry Shamet', position: 'SG', overall: 73 },
],
'Indiana Pacers': [
  { playerName: 'Devin Booker', position: 'PG', overall: 92 },
  { playerName: 'De\'Aaron Fox', position: 'PG', overall: 86 },
  { playerName: 'Jabari Smith Jr.', position: 'PF', overall: 81 },
  { playerName: 'Daniel Gafford', position: 'C', overall: 81 },
  { playerName: 'Nickeil Alexander-Walker', position: 'SG', overall: 80 },
  { playerName: 'Kris Dunn', position: 'SG', overall: 77 },
  { playerName: 'Corey Kispert', position: 'SF', overall: 77 },
  { playerName: 'Jordan Walker', position: 'SF', overall: 77 },
  { playerName: 'Marvin Bagley III', position: 'C', overall: 76 },
  { playerName: 'Kelly Olynyk', position: 'PF', overall: 76 },
  { playerName: 'Larry Nance Jr.', position: 'C', overall: 74 },
  { playerName: 'Monte Morris', position: 'PG', overall: 74 },
  { playerName: 'Jordan Walter', position: 'SG', overall: 73 },
  { playerName: 'Ochai Agbaji', position: 'PF', overall: 73 },
],
  'New Orleans Pelicans': [
  { playerName: 'James Harden', position: 'PG', overall: 89 },
  { playerName: 'Franz Wagner', position: 'SF', overall: 86 },
  { playerName: 'Derrick White', position: 'SG', overall: 84 },
  { playerName: 'Nikola Vucevic', position: 'C', overall: 83 },
  { playerName: 'Wendell Carter Jr.', position: 'C', overall: 79 },
  { playerName: 'Lonzo Ball', position: 'PG', overall: 77 },
  { playerName: 'Nick Richards', position: 'C', overall: 76 },
  { playerName: 'Petteri Larsson', position: 'SG', overall: 75 },
  { playerName: 'Darius Queen', position: 'PF', overall: 74 },
  { playerName: 'Jeremiah Robinson-Earl', position: 'PF', overall: 74 },
  { playerName: 'Gary Payton II', position: 'SG', overall: 73 },
  { playerName: 'Julian Champagnie', position: 'SF', overall: 73 },
  { playerName: 'Jett Howard', position: 'SG', overall: 72 },
  { playerName: 'KJ Simpson', position: 'PG', overall: 72 },
],
  'Detroit Pistons': [
  { playerName: 'Evan Mobley', position: 'PF', overall: 90 },
  { playerName: 'Tyler Herro', position: 'PG', overall: 87 },
  { playerName: 'Jalen Duren', position: 'C', overall: 84 },
  { playerName: 'Cam Thomas', position: 'SG', overall: 81 },
  { playerName: 'Alex Caruso', position: 'SF', overall: 81 },
  { playerName: 'Andrew Wiggins', position: 'SF', overall: 81 },
  { playerName: 'Moussa Diabate', position: 'C', overall: 78 },
  { playerName: 'Malcolm Brogdon', position: 'PG', overall: 78 },
  { playerName: 'Duncan Robinson', position: 'SG', overall: 77 },
  { playerName: 'GG Jackson', position: 'PF', overall: 75 },
  { playerName: 'Marcus Sasser', position: 'PG', overall: 75 },
  { playerName: 'Trey Lyles', position: 'PF', overall: 75 },
  { playerName: 'Paul Reed', position: 'PF', overall: 73 },
  { playerName: 'Jalen Green', position: 'SF', overall: 73 },
  { playerName: 'Walt Riley', position: 'SF', overall: 71 },
],
'Toronto Raptors': [
  { playerName: 'Jalen Brunson', position: 'PG', overall: 93 },
  { playerName: 'Karl-Anthony Towns', position: 'PF', overall: 91 },
  { playerName: 'Norman Powell', position: 'SG', overall: 85 },
  { playerName: 'Naz Reid', position: 'C', overall: 82 },
  { playerName: 'Bennedict Mathurin', position: 'SF', overall: 81 },
  { playerName: 'Payton Pritchard', position: 'PG', overall: 81 },
  { playerName: 'Jaime Jaquez Jr.', position: 'SF', overall: 80 },
  { playerName: 'Santi Aldama', position: 'PF', overall: 79 },
  { playerName: 'Buddy Hield', position: 'SG', overall: 77 },
  { playerName: 'Jalen Williams', position: 'C', overall: 75 },
  { playerName: 'Kevon Looney', position: 'C', overall: 75 },
  { playerName: 'Trey Martin', position: 'SG', overall: 74 },
  { playerName: 'Vít Krejčí', position: 'SF', overall: 73 },
  { playerName: 'Nikola Topić', position: 'PG', overall: 72 },
],
'Houston Rockets': [
  { playerName: 'Chet Holmgren', position: 'PF', overall: 88 },
  { playerName: 'OG Anunoby', position: 'SF', overall: 86 },
  { playerName: 'Andrew Nembhard', position: 'PG', overall: 81 },
  { playerName: 'Nic Claxton', position: 'C', overall: 80 },
  { playerName: 'Jaden Ivey', position: 'SG', overall: 80 },
  { playerName: 'Kobe Knueppel', position: 'SG', overall: 79 },
  { playerName: 'Keldon Johnson', position: 'SF', overall: 78 },
  { playerName: 'Luke Kornet', position: 'C', overall: 77 },
  { playerName: 'Reed Sheppard', position: 'PG', overall: 76 },
  { playerName: 'Isaiah Jackson', position: 'C', overall: 74 },
  { playerName: 'Julian Champagnie', position: 'PF', overall: 74 },
  { playerName: 'Amir Coffey', position: 'SF', overall: 74 },
  { playerName: 'Noah Essengue', position: 'PF', overall: 72 },
  { playerName: 'John Furphy', position: 'SG', overall: 70 },
  { playerName: 'Rokas Zilarksy', position: 'C', overall: 68 },
],
'San Antonio Spurs': [
  { playerName: 'Joel Embiid', position: 'C', overall: 90 },
  { playerName: 'Brandon Miller', position: 'SF', overall: 83 },
  { playerName: 'Jonathan Kuminga', position: 'PF', overall: 81 },
  { playerName: 'Cooper Flagg', position: 'SF', overall: 81 },
  { playerName: 'Ron Holland', position: 'PF', overall: 77 },
  { playerName: 'Andre Drummond', position: 'C', overall: 77 },
  { playerName: 'Wendell Richard', position: 'SG', overall: 76 },
  { playerName: 'Quenton Jackson', position: 'PG', overall: 75 },
  { playerName: 'AJ Johnson', position: 'SG', overall: 75 },
  { playerName: 'Jaden Hardy', position: 'SG', overall: 74 },
  { playerName: 'AJ Lawson', position: 'SF', overall: 74 },
  { playerName: 'Ashton Newell', position: 'PF', overall: 73 },
  { playerName: 'Egor Demin', position: 'PG', overall: 73 },
  { playerName: 'Young Hansen', position: 'C', overall: 70 },
],
'Phoenix Suns'Minnesota Timberwolves': [
  { playerName: 'Jalen Williams', position: 'SF', overall: 91 },
  { playerName: 'Paolo Banchero', position: 'PF', overall: 90 },
  { playerName: 'Rudy Gobert', position: 'C', overall: 84 },
  { playerName: 'Jalen Green', position: 'SG', overall: 83 },
  { playerName: 'Jahmir Fears', position: 'PG', overall: 78 },
  { playerName: 'Gradey Dick', position: 'SF', overall: 77 },
  { playerName: 'Keon Ellis', position: 'SG', overall: 76 },
  { playerName: 'Josh Minott', position: 'PF', overall: 76 },
  { playerName: 'Rob Dillingham', position: 'PG', overall: 73 },
  { playerName: 'Blake Wesley', position: 'PG', overall: 73 },
  { playerName: 'Jabari Walker', position: 'PF', overall: 73 },
  { playerName: 'Mo Bamba', position: 'C', overall: 72 },
  { playerName: 'Damian Powell', position: 'SG', overall: 70 },
  { playerName: 'Hector Gonzalez', position: 'SF', overall: 70 },
],
': [
  { playerName: 'LeBron James', position: 'SF', overall: 95 },
  { playerName: 'Josh Giddey', position: 'PG', overall: 86 },
  { playerName: 'DeMar DeRozan', position: 'SF', overall: 86 },
  { playerName: 'Russell Westbrook', position: 'PG', overall: 81 },
  { playerName: 'Obi Toppin', position: 'PF', overall: 80 },
  { playerName: 'Mark Williams', position: 'C', overall: 80 },
  { playerName: 'Grayson Allen', position: 'SG', overall: 78 },
  { playerName: 'Ryan Dunn', position: 'PF', overall: 77 },
  { playerName: 'Ayo Dosunmu', position: 'SG', overall: 77 },
  { playerName: 'Jabari Smith', position: 'C', overall: 75 },
  { playerName: 'Drew Eubanks', position: 'C', overall: 75 },
  { playerName: 'Jamelle Shead', position: 'PG', overall: 74 },
  { playerName: 'Dalen Terry', position: 'SG', overall: 73 },
  { playerName: 'Gui Santos', position: 'PF', overall: 73 },
],
'Oklahoma City Thunder': [
  { playerName: 'Cade Cunningham', position: 'PG', overall: 92 },
  { playerName: 'Lauri Markkanen', position: 'SF', overall: 87 },
  { playerName: 'Kristaps Porzingis', position: 'C', overall: 85 },
  { playerName: 'Devin Vassell', position: 'SG', overall: 84 },
  { playerName: 'Tari Eason', position: 'SF', overall: 80 },
  { playerName: 'Davion Mitchell', position: 'PG', overall: 79 },
  { playerName: 'Brice Sensabaugh', position: 'SG', overall: 76 },
  { playerName: 'Mouhamed Gueye', position: 'PF', overall: 75 },
  { playerName: 'Dean Wade', position: 'PF', overall: 74 },
  { playerName: 'Nick Smith Jr.', position: 'PG', overall: 74 },
  { playerName: 'Kenyon Martin Jr.', position: 'PF', overall: 74 },
  { playerName: 'Charles Bassey', position: 'C', overall: 73 },
  { playerName: 'Julian Phillips', position: 'SF', overall: 72 },
  { playerName: 'Malaki Branham', position: 'SG', overall: 72 },
],
'Portland Trail Blazers': [
  { playerName: 'Giannis Antetokounmpo', position: 'PF', overall: 98 },
  { playerName: 'Trae Young', position: 'PG', overall: 89 },
  { playerName: 'Brandon Ingram', position: 'SF', overall: 85 },
  { playerName: 'Onyeka Okongwu', position: 'C', overall: 82 },
  { playerName: 'Malik Monk', position: 'SG', overall: 81 },
  { playerName: 'Ty Jerome', position: 'PG', overall: 80 },
  { playerName: 'Josh Hart', position: 'PF', overall: 79 },
  { playerName: 'Brandin Podziemski', position: 'SG', overall: 79 },
  { playerName: 'Miles McBride', position: 'PG', overall: 76 },
  { playerName: 'Nicolas Batum', position: 'SF', overall: 76 },
  { playerName: 'Karlo Matkovic', position: 'PF', overall: 75 },
  { playerName: 'Olivier-Maxence Prosper', position: 'PF', overall: 74 },
  { playerName: 'Dariq Whitehead', position: 'SG', overall: 72 },
  { playerName: 'Tristan Vukcevic', position: 'C', overall: 72 },
],
'Golden State Warriors': [
  { playerName: 'Anthony Edwards', position: 'SG', overall: 95 },
  { playerName: 'Domantas Sabonis', position: 'C', overall: 86 },
  { playerName: 'De\'Andre Hunter', position: 'SF', overall: 80 },
  { playerName: 'Keegan Murray', position: 'PF', overall: 80 },
  { playerName: 'Anthony Black', position: 'PG', overall: 79 },
  { playerName: 'Steven Adams', position: 'C', overall: 77 },
  { playerName: 'Gary Trent Jr.', position: 'SF', overall: 77 },
  { playerName: 'Scotty Pippen Jr.', position: 'PG', overall: 77 },
  { playerName: 'Adem Bona', position: 'C', overall: 74 },
  { playerName: 'Keyontae Johnson', position: 'SG', overall: 74 },
  { playerName: 'Shake Milton', position: 'PG', overall: 72 },
  { playerName: 'Tidjane Salaun', position: 'PF', overall: 72 },
  { playerName: 'Nassir Clifford', position: 'SF', overall: 72 },
  { playerName: 'Rayshon Fleming', position: 'PF', overall: 70 },
],
'Washington Wizards': [
  { playerName: 'Nikola Jokic', position: 'C', overall: 98 },
  { playerName: 'Stephon Castle', position: 'PG', overall: 84 },
  { playerName: 'Trey Murphy III', position: 'SG', overall: 80 },
  { playerName: 'Zaccharie Risacher', position: 'SF', overall: 78 },
  { playerName: 'Cody Murray-Boyles', position: 'PF', overall: 77 },
  { playerName: 'Royce O\'Neale', position: 'SF', overall: 77 },
  { playerName: 'Kevin Porter Jr.', position: 'PG', overall: 76 },
  { playerName: 'AJ Green', position: 'SG', overall: 76 },
  { playerName: 'Jaden Edwards', position: 'SF', overall: 76 },
  { playerName: 'Georges Niang', position: 'PF', overall: 75 },
  { playerName: 'Kyal Maluach', position: 'C', overall: 74 },
  { playerName: 'Craig Spencer', position: 'PG', overall: 74 },
  { playerName: 'Jordan Goodwin', position: 'SG', overall: 74 },
  { playerName: 'Ousmane Dieng', position: 'PF', overall: 73 },
],
'Philadelphia 76ers': [
  { playerName: 'Damian Lillard', position: 'PG', overall: 89 },
  { playerName: 'Jaden McDaniels', position: 'SF', overall: 83 },
  { playerName: 'Walker Kessler', position: 'C', overall: 83 },
  { playerName: 'Anfernee Simons', position: 'SG', overall: 82 },
  { playerName: 'Khris Middleton', position: 'PF', overall: 79 },
  { playerName: 'Tre Jones', position: 'PG', overall: 79 },
  { playerName: 'Clint Capela', position: 'C', overall: 78 },
  { playerName: 'Isaiah Stewart', position: 'C', overall: 77 },
  { playerName: 'Sam Hauser', position: 'SF', overall: 77 },
  { playerName: 'Matisse Thybulle', position: 'SG', overall: 75 },
  { playerName: 'Simone Fontecchio', position: 'PF', overall: 75 },
  { playerName: 'De\'Anthony Melton', position: 'SG', overall: 75 },
  { playerName: 'Haywood Highsmith', position: 'SF', overall: 74 },
  { playerName: 'Lindy Waters III', position: 'SG', overall: 73 },
  { playerName: 'Jaden Springer', position: 'SG', overall: 72 },
],
'Milwaukee Bucks': [
  { playerName: 'Bam Adebayo', position: 'PF', overall: 89 },
  { playerName: 'Jamal Murray', position: 'PG', overall: 87 },
  { playerName: 'Michael Porter Jr.', position: 'PF', overall: 83 },
  { playerName: 'Desmond Bane', position: 'SG', overall: 82 },
  { playerName: 'Rui Hachimura', position: 'PF', overall: 81 },
  { playerName: 'Jakob Poeltl', position: 'C', overall: 80 },
  { playerName: 'Isaiah Collier', position: 'PG', overall: 79 },
  { playerName: 'Bradley Beal', position: 'SG', overall: 79 },
  { playerName: 'Jaxson Hayes', position: 'C', overall: 76 },
  { playerName: 'Jaylen Clark', position: 'SF', overall: 74 },
  { playerName: 'Terry Rozier III', position: 'PG', overall: 74 },
  { playerName: 'Cody Williams', position: 'SF', overall: 73 },
  { playerName: 'Jamarion Beringer', position: 'C', overall: 71 },
  { playerName: 'Julian Richardson', position: 'SG', overall: 71 },
],
'Chicago Bulls': [
  { playerName: 'Donovan Mitchell', position: 'SG', overall: 94 },
  { playerName: 'Jalen Johnson', position: 'PF', overall: 83 },
  { playerName: 'Vyctorius Edgecombe', position: 'SG', overall: 81 },
  { playerName: 'Cason Wallace', position: 'SG', overall: 80 },
  { playerName: 'Christian Braun', position: 'SG', overall: 80 },
  { playerName: 'Dennis Schröder', position: 'PG', overall: 79 },
  { playerName: 'Mitchell Robinson', position: 'C', overall: 79 },
  { playerName: 'Chris Paul', position: 'PG', overall: 77 },
  { playerName: 'Sandro Mamukelashvili', position: 'C', overall: 76 },
  { playerName: 'Taylor Hendricks', position: 'PF', overall: 75 },
  { playerName: 'Maxi Kleber', position: 'PF', overall: 73 },
  { playerName: 'Kevin Love', position: 'C', overall: 73 },
  { playerName: 'Cody Bryant', position: 'SF', overall: 72 },
  { playerName: 'Ben Saraf', position: 'PG', overall: 72 },
  { playerName: 'Tyrese Proctor', position: 'SG', overall: 69 },
],
'Cleveland Cavaliers': [
  { playerName: 'Luka Dončić', position: 'PG', overall: 97 },
  { playerName: 'Jarrett Allen', position: 'C', overall: 85 },
  { playerName: 'Aaron Gordon', position: 'PF', overall: 83 },
  { playerName: 'Shaedon Sharpe', position: 'SG', overall: 82 },
  { playerName: 'Donte DiVincenzo', position: 'PG', overall: 79 },
  { playerName: 'Robert Williams III', position: 'C', overall: 79 },
  { playerName: 'Terance Mann', position: 'SF', overall: 78 },
  { playerName: 'Mike Conley', position: 'PG', overall: 78 },
  { playerName: 'Kentavious Caldwell-Pope', position: 'SG', overall: 77 },
  { playerName: 'Kyle Filipowski', position: 'PF', overall: 76 },
  { playerName: 'Jett Howard', position: 'SF', overall: 73 },
  { playerName: 'James Wiseman', position: 'C', overall: 73 },
  { playerName: 'Liam McNeeley', position: 'SF', overall: 71 },
],
'Boston Celtics': [
  { playerName: 'Ja Morant', position: 'PG', overall: 90 },
  { playerName: 'Zion Williamson', position: 'PF', overall: 87 },
  { playerName: 'Jordan Poole', position: 'SG', overall: 81 },
  { playerName: 'Cam Johnson', position: 'SF', overall: 80 },
  { playerName: 'Daquan Harper', position: 'SG', overall: 79 },
  { playerName: 'Bilal Coulibaly', position: 'SG', overall: 79 },
  { playerName: 'Brandon Clarke', position: 'C', overall: 79 },
  { playerName: 'Dorian Finney-Smith', position: 'PF', overall: 77 },
  { playerName: 'Tremont Johnson', position: 'SG', overall: 76 },
  { playerName: 'Jock Landale', position: 'C', overall: 76 },
  { playerName: 'John Konchar', position: 'SF', overall: 75 },
  { playerName: 'Tre Jones', position: 'PG', overall: 75 },
  { playerName: 'Richaun Holmes', position: 'C', overall: 74 },
  { playerName: 'Caleb Martin', position: 'PF', overall: 74 },
],
'Los Angeles Clippers': [
  { playerName: 'Kawhi Leonard', position: 'SF', overall: 93 },
  { playerName: 'Austin Reaves', position: 'SG', overall: 89 },
  { playerName: 'Darius Garland', position: 'PG', overall: 88 },
  { playerName: 'Mikal Bridges', position: 'PF', overall: 82 },
  { playerName: 'Jerami Grant', position: 'PF', overall: 81 },
  { playerName: 'Yves Missi', position: 'C', overall: 80 },
  { playerName: 'Isaiah Joe', position: 'SG', overall: 79 },
  { playerName: 'Immanuel Quickley', position: 'PG', overall: 79 },
  { playerName: 'Max Strus', position: 'SF', overall: 78 },
  { playerName: 'Moritz Wagner', position: 'C', overall: 76 },
  { playerName: 'Zach Collins', position: 'PF', overall: 75 },
  { playerName: 'Gabe Vincent', position: 'PG', overall: 75 },
  { playerName: 'Chris Boucher', position: 'PF', overall: 74 },
  { playerName: 'Johnny Juzang', position: 'SG', overall: 73 },
],
'Memphis Grizzlies': [
  { playerName: 'Shai Gilgeous-Alexander', position: 'PG', overall: 98 },
  { playerName: 'Amen Thompson', position: 'SF', overall: 82 },
  { playerName: 'Myles Turner', position: 'C', overall: 81 },
  { playerName: 'Herb Jones', position: 'SF', overall: 80 },
  { playerName: 'Kel’el Ware', position: 'C', overall: 79 },
  { playerName: 'Jeremy Sochan', position: 'PF', overall: 77 },
  { playerName: 'Klay Thompson', position: 'SG', overall: 76 },
  { playerName: 'Cam Whitmore', position: 'SG', overall: 75 },
  { playerName: 'Terance Mann', position: 'PG', overall: 75 },
  { playerName: 'Isaac Okoro', position: 'SF', overall: 74 },
  { playerName: 'Dario Saric', position: 'PF', overall: 74 },
  { playerName: 'Terrence Shannon Jr.', position: 'SG', overall: 73 },
  { playerName: 'Reggie Jackson', position: 'PG', overall: 73 },
  { playerName: 'Kobe Bufkin', position: 'PG', overall: 71 },
  { playerName: 'Tristan Thompson', position: 'C', overall: 70 },
],
'Atlanta Hawks': [
  { playerName: 'Dyson Daniels', position: 'SG', overall: 83 },
  { playerName: 'Cameron Coward', position: 'SF', overall: 80 },
  { playerName: 'Scoot Henderson', position: 'PG', overall: 78 },
  { playerName: 'Precious Achiuwa', position: 'PF', overall: 77 },
  { playerName: 'Jalen Wells', position: 'SF', overall: 76 },
  { playerName: 'Nikola Jovic', position: 'PF', overall: 75 },
  { playerName: 'Bogdan Bogdanovic', position: 'SG', overall: 75 },
  { playerName: 'James Nagbe (Mogbo)', position: 'C', overall: 74 },
  { playerName: 'Julian Strawther', position: 'SG', overall: 74 },
  { playerName: 'Andre Bailey', position: 'SF', overall: 74 },
  { playerName: 'Thomas Bryant', position: 'C', overall: 74 },
  { playerName: 'C. Porter Jr.', position: 'PG', overall: 73 },
  { playerName: 'K. Jakucionis', position: 'PG', overall: 72 },
  { playerName: 'D. Wolf', position: 'C', overall: 71 },
],
'Miami Heat': [
  { playerName: 'Tyrese Haliburton', position: 'PG', overall: 93 },
  { playerName: 'Alperen Sengun', position: 'C', overall: 88 },
  { playerName: 'Luguentz Dort', position: 'SG', overall: 81 },
  { playerName: 'Draymond Green', position: 'C', overall: 80 },
  { playerName: 'Tim Hardaway Jr.', position: 'SF', overall: 79 },
  { playerName: 'Marcus Smart', position: 'SG', overall: 79 },
  { playerName: 'Jake LaRavia', position: 'SF', overall: 78 },
  { playerName: 'D’Angelo Russell', position: 'PG', overall: 78 },
  { playerName: 'Cameron Payne', position: 'PG', overall: 76 },
  { playerName: 'Kyle Anderson', position: 'PF', overall: 75 },
  { playerName: 'Seth Curry', position: 'SG', overall: 75 },
  { playerName: 'Jonathan Isaac', position: 'PF', overall: 73 },
  { playerName: 'Noah Clowney', position: 'PF', overall: 73 },
  { playerName: 'Christian Wood', position: 'C', overall: 73 },
],
'Charlotte Hornets': [
  { playerName: 'Victor Wembanyama', position: 'C', overall: 96 },
  { playerName: 'Scottie Barnes', position: 'SF', overall: 86 },
  { playerName: 'Deni Avdija', position: 'PF', overall: 84 },
  { playerName: 'Donovan Mitchell', position: 'PG', overall: 78 },
  { playerName: 'Kyle Kuzma', position: 'PF', overall: 77 },
  { playerName: 'Spencer Dinwiddie', position: 'PG', overall: 77 },
  { playerName: 'Luke Kennard', position: 'SF', overall: 76 },
  { playerName: 'B. Sheppard', position: 'SG', overall: 74 },
  { playerName: 'Bol Bol', position: 'PF', overall: 74 },
  { playerName: 'J. Green', position: 'SF', overall: 74 },
  { playerName: 'Jae Crowder', position: 'PF', overall: 73 },
  { playerName: 'Dalano Banton', position: 'PG', overall: 73 },
  { playerName: 'Kessler Edwards', position: 'C', overall: 73 },
  { playerName: 'A. Jackson Jr.', position: 'SG', overall: 72 },
],
'Utah Jazz': [
  { playerName: 'Kevin Durant', position: 'SF', overall: 94 },
  { playerName: 'Jalen Suggs', position: 'PG', overall: 83 },
  { playerName: 'Toumani Camara', position: 'SF', overall: 80 },
  { playerName: 'Zach Edey', position: 'C', overall: 80 },
  { playerName: 'Harrison Barnes', position: 'PF', overall: 79 },
  { playerName: 'Damian Jones Jr.', position: 'PF', overall: 77 },
  { playerName: 'C. Carrington', position: 'PG', overall: 77 },
  { playerName: 'S. James', position: 'SG', overall: 76 },
  { playerName: 'Caris LeVert', position: 'SG', overall: 76 },
  { playerName: 'G. Williams', position: 'PF', overall: 75 },
  { playerName: 'Delon Wright', position: 'PG', overall: 73 },
  { playerName: 'Jordan Hawkins', position: 'SG', overall: 73 },
  { playerName: 'Cam Reddish', position: 'SF', overall: 72 },
  { playerName: 'Jericho Sims', position: 'C', overall: 72 },
],
'Sacramento Kings': [
  { playerName: 'Amen Thompson', position: 'PG', overall: 87 },
  { playerName: 'Alex Sarr', position: 'C', overall: 83 },
  { playerName: 'Collin Sexton', position: 'SG', overall: 81 },
  { playerName: 'Moses Moody', position: 'SF', overall: 78 },
  { playerName: 'Cole Anthony', position: 'PG', overall: 78 },
  { playerName: 'Jusuf Nurkic', position: 'C', overall: 78 },
  { playerName: 'P. Watson', position: 'PF', overall: 77 },
  { playerName: 'Ziaire Williams', position: 'SF', overall: 76 },
  { playerName: 'Bruce Brown', position: 'SG', overall: 76 },
  { playerName: 'B. Williams', position: 'PG', overall: 76 },
  { playerName: 'N. Penda', position: 'SF', overall: 74 },
  { playerName: 'T. Sorber', position: 'C', overall: 72 },
  { playerName: 'Dominick Barlow', position: 'PF', overall: 72 },
],
'New York Knicks': [
  { playerName: 'Jayson Tatum', position: 'PF', overall: 94 },
  { playerName: 'Kyrie Irving', position: 'PG', overall: 91 },
  { playerName: 'Zach LaVine', position: 'SG', overall: 86 },
  { playerName: 'Deandre Ayton', position: 'C', overall: 82 },
  { playerName: 'Kelly Oubre Jr.', position: 'SF', overall: 81 },
  { playerName: 'Andrew Wiggins', position: 'SF', overall: 80 },
  { playerName: 'Ryan Rollins', position: 'PG', overall: 79 },
  { playerName: 'Malik Beasley', position: 'SG', overall: 78 },
  { playerName: 'Guerschon Yabusele', position: 'C', overall: 76 },
  { playerName: 'Alec Burks', position: 'SG', overall: 75 },
  { playerName: 'D. Carter', position: 'PG', overall: 75 },
  { playerName: 'Trayce Jackson-Davis', position: 'C', overall: 74 },
  { playerName: 'D. Holmes II', position: 'PF', overall: 72 },
],
'Los Angeles Lakers': [
  { playerName: 'Stephen Curry', position: 'PG', overall: 95 },
  { playerName: 'Jimmy Butler', position: 'SF', overall: 88 },
  { playerName: 'Julius Randle', position: 'PF', overall: 87 },
  { playerName: 'Coby White', position: 'SG', overall: 84 },
  { playerName: 'Bobby Portis Jr.', position: 'C', overall: 81 },
  { playerName: 'Aaron Nesmith', position: 'SG', overall: 81 },
  { playerName: 'Tobias Harris', position: 'PF', overall: 80 },
  { playerName: 'CJ McCollum', position: 'PG', overall: 78 },
  { playerName: 'Al Horford', position: 'C', overall: 78 },
  { playerName: 'C. Gillespie', position: 'PG', overall: 76 },
  { playerName: 'T. Prince', position: 'SF', overall: 76 },
  { playerName: 'Bogdan Bogdanovic', position: 'SF', overall: 76 },
  { playerName: 'J. Huff', position: 'C', overall: 74 },
  { playerName: 'Gary Harris', position: 'SG', overall: 73 },
],
'Orlando Magic': [
  { playerName: 'LaMelo Ball', position: 'PG', overall: 88 },
  { playerName: 'Jaren Jackson Jr.', position: 'PF', overall: 88 },
  { playerName: 'Paul George', position: 'SF', overall: 81 },
  { playerName: 'Quentin Grimes', position: 'SG', overall: 78 },
  { playerName: 'Ryan Kalkbrenner', position: 'C', overall: 78 },
  { playerName: 'Ben Simmons', position: 'PG', overall: 78 },
  { playerName: 'Kevin Huerter', position: 'SF', overall: 77 },
  { playerName: 'Dalton Knecht', position: 'SG', overall: 77 },
  { playerName: 'Goga Bitadze', position: 'C', overall: 76 },
  { playerName: 'Saddiq Bey', position: 'SF', overall: 76 },
  { playerName: 'J. Battle', position: 'SF', overall: 75 },
  { playerName: 'Eric Gordon', position: 'SG', overall: 75 },
  { playerName: 'W. Clayton Jr.', position: 'PG', overall: 73 },
  { playerName: 'Zeke Nnaji', position: 'C', overall: 73 },
  { playerName: 'Jalen Hood-Schifino', position: 'SG', overall: 71 },
],
'Dallas Mavericks': [
  { playerName: 'Anthony Davis', position: 'PF', overall: 93 },
  { playerName: 'Jrue Holiday', position: 'PG', overall: 82 },
  { playerName: 'Dejounte Murray', position: 'PG', overall: 81 },
  { playerName: 'Dereck Lively II', position: 'C', overall: 80 },
  { playerName: 'P.J. Washington', position: 'SF', overall: 79 },
  { playerName: 'Brook Lopez', position: 'C', overall: 79 },
  { playerName: 'Naji Marshall', position: 'SF', overall: 77 },
  { playerName: 'Max Christie', position: 'SG', overall: 76 },
  { playerName: 'Sam Merrill', position: 'SG', overall: 76 },
  { playerName: 'Dante Exum', position: 'SG', overall: 75 },
  { playerName: 'Trendon Watford', position: 'PF', overall: 74 },
  { playerName: 'Keegan Murray', position: 'SF', overall: 74 },
  { playerName: 'Oso Ighodaro', position: 'C', overall: 73 },
  { playerName: 'Aaron Holiday', position: 'PG', overall: 73 },
  { playerName: 'Dwight Powell', position: 'C', overall: 73 },
]


};


async function seedDatabase() {
  try {
    await sequelize.authenticate();
    console.log('Database connected successfully.');

    await sequelize.sync({ force: true }); 
    console.log('Database synced.');

    for (const [teamName, players] of Object.entries(teamData)) {
      const team = await NBATeams.create({ teamName });

      for (const player of players) {
        await Player.create({
          playerName: player.playerName,
          position: player.position,
          overall: player.overall,
          teamId: team.id,
        });
      }
    }

    console.log('Seeded NBA teams and players.');
  } catch (err) {
    console.error('Error seeding database:', err);
  } finally {
    await sequelize.close();
  }
}

seedDatabase();
