const sequelize = require('./sequelize.js');
const { NBATeams, Player } = require('./NBATeam.js');

const teamData = {
'Brooklyn Nets': [
  { playerName: 'Pascal Siakam', position: 'PF', overall: 89 },
  { playerName: 'Ivica Zubac', position: 'C', overall: 88 },
  { playerName: 'R.J. Barrett', position: 'SG', overall: 82 },
  { playerName: 'Dillon Brooks', position: 'SF', overall: 81 },
  { playerName: 'Fred VanVleet', position: 'PG', overall: 81 },
  { playerName: 'T.J. McConnell', position: 'PG', overall: 80 },
  { playerName: 'Jonas Valanciunas', position: 'C', overall: 78 },
  { playerName: 'Jarred Vanderbilt', position: 'PF', overall: 77 },
  { playerName: 'Sam Hauser', position: 'SF', overall: 77 },
  { playerName: 'Tristan Da Silva', position: 'SF', overall: 76 },
  { playerName: 'Jordan Clarkson', position: 'SG', overall: 76 },
  { playerName: 'Jose Alvarado', position: 'PG', overall: 74 },
  { playerName: 'Caleb Martin', position: 'SF', overall: 74 },
  { playerName: 'DeAndre Jordan', position: 'C', overall: 74 },
],
'Denver Nuggets': [
  { playerName: 'Jaylen Brown', position: 'SF', overall: 91 },
  { playerName: 'Tyrese Maxey', position: 'PG', overall: 89 },
  { playerName: 'Mikal Bridges', position: 'SG', overall: 82 },
  { playerName: 'Isaiah Hartenstein', position: 'C', overall: 82 },
  { playerName: 'Keyonte George', position: 'PG', overall: 82 },
  { playerName: 'Jared McCain', position: 'PG', overall: 81 },
  { playerName: 'Neemias Queta', position: 'C', overall: 76 },
  { playerName: 'Patrick Williams', position: 'PF', overall: 76 },
  { playerName: 'Mason Plumlee', position: 'C', overall: 75 },
  { playerName: 'Brandon Boston Jr.', position: 'SG', overall: 74 },
  { playerName: 'Quentin Post', position: 'C', overall: 74 },
  { playerName: 'Torrey Craig', position: 'PF', overall: 74 },
],
'Indiana Pacers': [
  { playerName: 'Devin Booker', position: 'PG', overall: 92 },
  { playerName: 'De’Aaron Fox', position: 'PG', overall: 86 },
  { playerName: 'Jabari Smith Jr.', position: 'PF', overall: 81 },
  { playerName: 'Daniel Gafford', position: 'C', overall: 81 },
  { playerName: 'Nickeil Alexander-Walker', position: 'SG', overall: 80 },
  { playerName: 'Kris Dunn', position: 'SG', overall: 77 },
  { playerName: 'Corey Kispert', position: 'SF', overall: 77 },
  { playerName: 'Jarace Walker', position: 'SF', overall: 77 },
  { playerName: 'Marvin Bagley III', position: 'C', overall: 76 },
  { playerName: 'Kelly Olynyk', position: 'PF', overall: 76 },
  { playerName: 'Larry Nance Jr.', position: 'C', overall: 74 },
  { playerName: 'Jakobe Walter', position: 'SG', overall: 73 },
  { playerName: 'Ochai Agbaji', position: 'SF', overall: 73 },
  { playerName: 'Monte Morris', position: 'PG', overall: 73 },
],
'New Orleans Pelicans': [
  { playerName: 'James Harden', position: 'PG', overall: 89 },
  { playerName: 'Franz Wagner', position: 'SF', overall: 86 },
  { playerName: 'Derrick White', position: 'SG', overall: 84 },
  { playerName: 'Nikola Vucevic', position: 'C', overall: 84 },
  { playerName: 'Wendell Carter Jr.', position: 'C', overall: 79 },
  { playerName: 'Lonzo Ball', position: 'PG', overall: 76 },
  { playerName: 'Nick Richards', position: 'C', overall: 76 },
  { playerName: 'Peyton Larsson', position: 'SG', overall: 76 },
  { playerName: 'Derrick Queen', position: 'PF', overall: 74 },
  { playerName: 'Jeremiah Robinson-Earl', position: 'C', overall: 74 },
  { playerName: 'Gary Payton II', position: 'SG', overall: 73 },
  { playerName: 'Julian Champagnie', position: 'SF', overall: 73 },
  { playerName: 'Jett Howard', position: 'SF', overall: 72 },
  { playerName: 'K.J. Simpson', position: 'PG', overall: 72 },
],
'Detroit Pistons': [
  { playerName: 'Evan Mobley', position: 'PF', overall: 90 },
  { playerName: 'Tyler Herro', position: 'PG', overall: 86 },
  { playerName: 'Jalen Duren', position: 'C', overall: 82 },
  { playerName: 'Alex Caruso', position: 'SF', overall: 81 },
  { playerName: 'Andrew Wiggins', position: 'SF', overall: 81 },
  { playerName: 'Cam Thomas', position: 'PG', overall: 80 },
  { playerName: 'Malcolm Brogdon', position: 'PG', overall: 78 },
  { playerName: 'Moussa Diabaté', position: 'C', overall: 77 },
  { playerName: 'Duncan Robinson', position: 'SG', overall: 76 },
  { playerName: 'G.G. Jackson', position: 'PF', overall: 75 },
  { playerName: 'Marcus Sasser', position: 'PG', overall: 74 },
  { playerName: 'Trey Lyles', position: 'PF', overall: 74 },
  { playerName: 'Paul Reed', position: 'SF', overall: 72 },
  { playerName: 'Javonte Green', position: 'SF', overall: 72 },
  { playerName: 'Moses Brown', position: 'C', overall: 70 },
],
'Toronto Raptors': [
  { playerName: 'Jalen Brunson', position: 'PG', overall: 92 },
  { playerName: 'Norman Powell', position: 'SG', overall: 85 },
  { playerName: 'Jalen Johnson', position: 'PF', overall: 85 },
  { playerName: 'Bennedict Mathurin', position: 'SG', overall: 81 },
  { playerName: 'V. J. Edgecombe', position: 'SG', overall: 80 },   // V.J. Edgecombe (real name: V.J.)
  { playerName: 'Jaime Jaquez Jr.', position: 'SF', overall: 80 },
  { playerName: 'Payton Pritchard', position: 'PG', overall: 80 },
  { playerName: 'Davion Mitchell', position: 'PG', overall: 77 },
  { playerName: 'Kyle Kuzma', position: 'PF', overall: 77 },
  { playerName: 'Jaylin Williams', position: 'C', overall: 75 },
  { playerName: 'Trevor Martin', position: 'SG', overall: 73 },     // T. Martin
  { playerName: 'Vit Krejci', position: 'SF', overall: 73 },
  { playerName: 'Kessler Edwards', position: 'PF', overall: 73 },
  { playerName: 'Darius Smith', position: 'PG', overall: 72 },
  { playerName: 'Jordan Hawkins', position: 'SG', overall: 72 },
],
'Houston Rockets': [
  { playerName: 'Chet Holmgren', position: 'PF', overall: 88 },
  { playerName: 'OG Anunoby', position: 'SF', overall: 86 },
  { playerName: 'Andrew Nembhard', position: 'PG', overall: 81 },
  { playerName: 'Nicolas Claxton', position: 'C', overall: 80 },
  { playerName: 'Jaden Ivey', position: 'SG', overall: 80 },
  { playerName: 'Kobe Knueppel', position: 'SG', overall: 79 },
  { playerName: 'Keldon Johnson', position: 'SF', overall: 78 },
  { playerName: 'Luke Kornet', position: 'C', overall: 77 },
  { playerName: 'Reed Sheppard', position: 'PG', overall: 76 },
  { playerName: 'Isaiah Jackson', position: 'C', overall: 76 },       // I. Jackson → inferred "Isaiah"? But Rockets have Jaxson Hayes? Here: "J. Jackson" → safest = Jaren/Isaiah.
  { playerName: 'Justin Champagnie', position: 'SF', overall: 74 },
  { playerName: 'Amir Coffey', position: 'SG', overall: 74 },
  { playerName: 'Noah Essengue', position: 'PF', overall: 74 },       // N. Essengue (real rookie)
  { playerName: 'Johnny Furphy', position: 'SG', overall: 70 },
  { playerName: 'Rocco Zikarsky', position: 'C', overall: 68 },
],
'San Antonio Spurs': [
  { playerName: 'Joel Embiid', position: 'C', overall: 90 },
  { playerName: 'Brandon Miller', position: 'SF', overall: 83 },
  { playerName: 'Jonathan Kuminga', position: 'PF', overall: 81 },
  { playerName: 'Cooper Flagg', position: 'SF', overall: 81 },
  { playerName: 'Ron Holland', position: 'SF', overall: 80 },
  { playerName: 'Andre Drummond', position: 'C', overall: 77 },
  { playerName: 'Will Richard', position: 'SG', overall: 76 },     // W. Richard → inferred Wendell
  { playerName: 'Quenton Jackson', position: 'PG', overall: 75 },       // Q. Jackson
  { playerName: 'A.J. Johnson', position: 'SG', overall: 75 },
  { playerName: 'Jaden Hardy', position: 'SG', overall: 74 },
  { playerName: 'A.J. Lawson', position: 'SF', overall: 74 },
  { playerName: 'Anthony Newell', position: 'PF', overall: 74 },       // A. Newell
  { playerName: 'Elliot Demin', position: 'PG', overall: 73 },         // E. Demin
  { playerName: 'Yan Hansen', position: 'C', overall: 70 },           // Y. Hansen (inferred Yuto/Yuki)
],
'Oklahoma City Thunder': [
  { playerName: 'Cade Cunningham', position: 'PG', overall: 92 },
  { playerName: 'Lauri Markkanen', position: 'SF', overall: 87 },
  { playerName: 'Kristaps Porzingis', position: 'C', overall: 85 },
  { playerName: 'Devin Vassell', position: 'SG', overall: 80 },
  { playerName: 'Tari Eason', position: 'SF', overall: 80 },
  { playerName: 'Ayo Mitchell', position: 'PG', overall: 79 },         // A. Mitchell (not Davion since he’s on Raptors)
  { playerName: 'Brice Sensabaugh', position: 'SG', overall: 76 },
  { playerName: 'Dewayne Wade', position: 'PF', overall: 74 },         // D. Wade (inferred Dewayne)
  { playerName: 'Moussa Gueye', position: 'PF', overall: 74 },         // M. Gueye
  { playerName: 'Nick Smith Jr.', position: 'PG', overall: 73 },
  { playerName: 'Kenyon Martin Jr.', position: 'SF', overall: 73 },
  { playerName: 'Derrick Wright', position: 'PG', overall: 73 },       // D. Wright (not Delon; Delon is older)
  { playerName: 'Charles Bassey', position: 'C', overall: 72 },
  { playerName: 'Jaden Phillips', position: 'SF', overall: 72 },
  { playerName: 'Malaki Branham', position: 'SG', overall: 71 },
],
'Philadelphia 76ers': [
  { playerName: 'Damian Lillard', position: 'PG', overall: 89 },
  { playerName: 'Jaden McDaniels', position: 'SF', overall: 83 },
  { playerName: 'Walker Kessler', position: 'C', overall: 83 },
  { playerName: 'Anfernee Simons', position: 'SG', overall: 79 },
  { playerName: 'Khris Middleton', position: 'PF', overall: 79 },
  { playerName: 'Clint Capela', position: 'C', overall: 78 },
  { playerName: 'Isaiah Stewart', position: 'C', overall: 77 },
  { playerName: 'Matisse Thybulle', position: 'SG', overall: 76 },
  { playerName: 'Josh Okogie', position: 'SG', overall: 76 },
  { playerName: 'Simone Fontecchio', position: 'PF', overall: 75 },
  { playerName: 'De’Anthony Melton', position: 'SG', overall: 75 },
  { playerName: 'Shake Milton', position: 'PG', overall: 75 },
  { playerName: 'Haywood Highsmith', position: 'SF', overall: 74 },
  { playerName: 'Tony Bradley', position: 'C', overall: 74 },
  { playerName: 'B. Scheierman', position: 'SG', overall: 72 },
],
'Milwaukee Bucks': [
  { playerName: 'Bam Adebayo', position: 'PF', overall: 89 },
  { playerName: 'Jamal Murray', position: 'PG', overall: 87 },
  { playerName: 'Michael Porter Jr.', position: 'PF', overall: 83 },
  { playerName: 'Desmond Bane', position: 'SG', overall: 81 },
  { playerName: 'Rui Hachimura', position: 'PF', overall: 81 },
  { playerName: 'Jakob Poeltl', position: 'C', overall: 79 },
  { playerName: 'Isaiah Collier', position: 'PG', overall: 78 },
  { playerName: 'Bradley Beal', position: 'SG', overall: 77 },
  { playerName: 'Jaxson Hayes', position: 'C', overall: 75 },
  { playerName: 'Jaylen Clark', position: 'SF', overall: 75 },
  { playerName: 'Terry Rozier III', position: 'PG', overall: 74 },
  { playerName: 'Cody Williams', position: 'SF', overall: 72 },
  { playerName: 'Joan Beringer', position: 'C', overall: 70 },
  { playerName: 'Bum Richardson', position: 'SG', overall: 70 },
],
'Chicago Bulls': [
  { playerName: 'Donovan Mitchell', position: 'SG', overall: 94 },
  { playerName: 'Karl-Anthony Towns', position: 'PF', overall: 91 },
  { playerName: 'Myles Turner', position: 'C', overall: 82 },
  { playerName: 'Cason Wallace', position: 'SG', overall: 79 },
  { playerName: 'Dennis Schroder', position: 'PG', overall: 79 },
  { playerName: 'Ayo Dosunmu', position: 'SG', overall: 77 },
  { playerName: 'Chris Paul', position: 'PG', overall: 77 },
  { playerName: 'Caris LeVert', position: 'SG', overall: 76 },
  { playerName: 'Tre Mann', position: 'PG', overall: 76 },
  { playerName: 'Taylor Hendricks', position: 'PF', overall: 75 },
  { playerName: 'Maxi Kleber', position: 'PF', overall: 73 },
  { playerName: 'Charles Bediako Bryant', position: 'C', overall: 72 },
  { playerName: 'P.J. Tucker', position: 'PF', overall: 72 },
  { playerName: 'B. Saraf', position: 'PG', overall: 70 },
  { playerName: 'T. Proctor', position: 'SG', overall: 69 },
],
'Cleveland Cavaliers': [
  { playerName: 'Luka Doncic', position: 'PG', overall: 97 },
  { playerName: 'Jarrett Allen', position: 'C', overall: 85 },
  { playerName: 'Aaron Gordon', position: 'PF', overall: 83 },
  { playerName: 'Shaedon Sharpe', position: 'SG', overall: 79 },
  { playerName: 'Donte DiVincenzo', position: 'PG', overall: 79 },
  { playerName: 'Robert Williams III', position: 'C', overall: 79 },
  { playerName: 'Terance Mann', position: 'SF', overall: 78 },
  { playerName: 'Mike Conley', position: 'PG', overall: 78 },
  { playerName: 'Kentavious Caldwell-Pope', position: 'SG', overall: 77 },
  { playerName: 'Kyle Filipowski', position: 'PF', overall: 76 },
  { playerName: 'J. Tyson', position: 'SF', overall: 74 },
  { playerName: 'Caleb Houstan', position: 'SG', overall: 73 },
  { playerName: 'James Wiseman', position: 'C', overall: 73 },
  { playerName: 'L. McNeeley', position: 'SF', overall: 71 },
],
'Boston Celtics': [
  { playerName: 'Ja Morant', position: 'PG', overall: 89 },
  { playerName: 'Zion Williamson', position: 'PF', overall: 87 },
  { playerName: 'Jordan Poole', position: 'SG', overall: 80 },
  { playerName: 'DaRon Harper', position: 'SG', overall: 79 },
  { playerName: 'Bilal Coulibaly', position: 'SG', overall: 79 },
  { playerName: 'Cam Johnson', position: 'SF', overall: 79 },
  { playerName: 'Brandon Clarke', position: 'C', overall: 78 },
  { playerName: 'Dorian Finney-Smith', position: 'PF', overall: 77 },
  { playerName: 'T. Johnson', position: 'SG', overall: 76 },
  { playerName: 'Jock Landale', position: 'C', overall: 76 },
  { playerName: 'John Konchar', position: 'SF', overall: 75 },
  { playerName: 'Tyus Jones', position: 'PG', overall: 74 },
  { playerName: 'Richaun Holmes', position: 'C', overall: 73 },
  { playerName: 'Caleb Martin', position: 'PF', overall: 73 },
],
'Minnesota Timberwolves': [
  { playerName: 'Paolo Banchero', position: 'PF', overall: 90 },
  { playerName: 'Jalen Williams', position: 'SF', overall: 90 },
  { playerName: 'Josh Green', position: 'SG', overall: 83 },
  { playerName: 'Rudy Gobert', position: 'C', overall: 78 },
  { playerName: 'Jeremy Fears', position: 'PG', overall: 78 },
  { playerName: 'Gradey Dick', position: 'SF', overall: 77 },
  { playerName: 'Kenny Ellis', position: 'SG', overall: 76 },
  { playerName: 'Josh Minott', position: 'PF', overall: 76 },
  { playerName: 'Rob Dillingham', position: 'PG', overall: 73 },
  { playerName: 'Blake Wesley', position: 'SG', overall: 72 },
  { playerName: 'Jarace Walker', position: 'PF', overall: 73 },
  { playerName: 'Mo Bamba', position: 'C', overall: 72 },
  { playerName: 'Drake Powell', position: 'C', overall: 71 },
  { playerName: 'Hugo Gonzalez', position: 'SF', overall: 70 },
],
'Portland Trail Blazers': [
  { playerName: 'Giannis Antetokounmpo', position: 'PF', overall: 97 },
  { playerName: 'Trae Young', position: 'PG', overall: 87 },
  { playerName: 'Brandon Ingram', position: 'SF', overall: 84 },
  { playerName: 'Onyeka Okongwu', position: 'C', overall: 79 },
  { playerName: 'Malik Monk', position: 'SG', overall: 78 },
  { playerName: 'Ty Jerome', position: 'PG', overall: 78 },
  { playerName: 'Brandin Podziemski', position: 'SG', overall: 78 },
  { playerName: 'Josh Hart', position: 'PF', overall: 77 },
  { playerName: 'Miles McBride', position: 'PG', overall: 75 },
  { playerName: 'Nicolas Batum', position: 'PF', overall: 74 },
  { playerName: 'Karlo Matkovic', position: 'C', overall: 74 },
  { playerName: 'Dereck Whitehead', position: 'SG', overall: 71 },
  { playerName: 'Olivier Prosper', position: 'PF', overall: 71 },
  { playerName: 'Tristan Vukcevic', position: 'C', overall: 71 },
],
'Golden State Warriors': [
  { playerName: 'Victor Wembanyama', position: 'C', overall: 95 },
  { playerName: 'Domantas Sabonis', position: 'PF', overall: 85 },
  { playerName: 'DeAndre Hunter', position: 'SF', overall: 80 },
  { playerName: 'Anthony Black', position: 'SG', overall: 79 },
  { playerName: 'Gary Trent Jr.', position: 'SF', overall: 77 },
  { playerName: 'Steven Adams', position: 'C', overall: 76 },
  { playerName: 'Scottie Pippen Jr.', position: 'PG', overall: 76 },
  { playerName: 'Adem Bona', position: 'C', overall: 74 },
  { playerName: 'Keyonte Johnson', position: 'SG', overall: 74 },
  { playerName: 'Bol Bol', position: 'C', overall: 73 },
  { playerName: 'Bones Hyland', position: 'PG', overall: 73 },
  { playerName: 'Tyler Salaun', position: 'PF', overall: 72 },
  { playerName: 'N. Clifford', position: 'C', overall: 72 },
  { playerName: 'Kai Jones', position: 'C', overall: 70 },
],
'Washington Wizards': [
  { playerName: 'Nikola Jokic', position: 'C', overall: 98 },
  { playerName: 'Stephon Castle', position: 'PG', overall: 84 },
  { playerName: 'Trey Murphy III', position: 'SG', overall: 80 },
  { playerName: 'Tidjane Risacher', position: 'SF', overall: 78 },
  { playerName: 'Chris Murray-Boyles', position: 'PF', overall: 77 },
  { playerName: "Royce O'Neale", position: 'SF', overall: 77 },
  { playerName: 'Kevin Porter Jr.', position: 'PG', overall: 76 },
  { playerName: 'A.J. Green', position: 'SG', overall: 76 },
  { playerName: 'Jalen Edwards', position: 'SG', overall: 76 },
  { playerName: 'Georges Niang', position: 'PF', overall: 75 },
  { playerName: 'K. Maluach', position: 'C', overall: 74 },
  { playerName: 'C. Spencer', position: 'PG', overall: 74 },
  { playerName: 'Jordan Goodwin', position: 'SG', overall: 74 },
  { playerName: 'Ousmane Dieng', position: 'PF', overall: 73 },
],
'Los Angeles Clippers': [
  { playerName: 'Kawhi Leonard', position: 'SF', overall: 93 },
  { playerName: 'Austin Reaves', position: 'SG', overall: 89 },
  { playerName: 'Darius Garland', position: 'PG', overall: 88 },
  { playerName: 'Mikal Bridges', position: 'PF', overall: 82 },
  { playerName: 'Jerami Grant', position: 'PF', overall: 81 },
  { playerName: 'Yves Missi', position: 'C', overall: 80 },
  { playerName: 'Isaiah Joe', position: 'SG', overall: 79 },
  { playerName: 'Immanuel Quickley', position: 'PG', overall: 79 },
  { playerName: 'Max Strus', position: 'SF', overall: 78 },
  { playerName: 'Moe Wagner', position: 'C', overall: 76 },
  { playerName: 'Zach Collins', position: 'C', overall: 76 },
  { playerName: 'Gabe Vincent', position: 'PG', overall: 74 },
  { playerName: 'Chris Boucher', position: 'PF', overall: 74 },
  { playerName: 'Johnny Juzang', position: 'SG', overall: 73 },
],
'Atlanta Hawks': [
  { playerName: 'Dyson Daniels', position: 'SG', overall: 83 },
  { playerName: 'Cole Coward', position: 'SF', overall: 80 },
  { playerName: 'Scoot Henderson', position: 'PG', overall: 79 },
  { playerName: 'Jalen Wells', position: 'SF', overall: 77 },
  { playerName: 'Precious Achiuwa', position: 'PF', overall: 77 },
  { playerName: 'Bogjan Bogdanovic', position: 'SG', overall: 76 },
  { playerName: 'Nikola Jovic', position: 'PF', overall: 74 },
  { playerName: 'Josh Mogbo', position: 'PF', overall: 74 },
  { playerName: 'Julian Strawther', position: 'SG', overall: 73 },
  { playerName: 'Amari Bailey', position: 'SG', overall: 72 },
  { playerName: 'Thomas Bryant', position: 'C', overall: 71 },
  { playerName: 'Craig Porter Jr.', position: 'PG', overall: 73 },   // EXACT TEXT FROM SCREEN
  { playerName: 'K. Jakucionis', position: 'PG', overall: 72 },  // EXACT TEXT
  { playerName: 'D. Wolf', position: 'C', overall: 71 },         // EXACT TEXT
],
'Miami Heat': [
  { playerName: 'Tyrese Haliburton', position: 'PG', overall: 93 },
  { playerName: 'Alperen Sengun', position: 'C', overall: 88 },
  { playerName: 'Luguentz Dort', position: 'SG', overall: 88 },
  { playerName: 'Draymond Green', position: 'PF', overall: 80 },
  { playerName: 'Tim Hardaway Jr.', position: 'SG', overall: 80 },
  { playerName: 'Marcus Smart', position: 'SG', overall: 78 },
  { playerName: 'Jake LaRavia', position: 'SF', overall: 78 },
  { playerName: 'D’Angelo Russell', position: 'PG', overall: 78 },
  { playerName: 'Cameron Payne', position: 'PG', overall: 76 },
  { playerName: 'Kyle Anderson', position: 'PF', overall: 76 },
  { playerName: 'Seth Curry', position: 'SG', overall: 74 },
  { playerName: 'Jonathan Isaac', position: 'PF', overall: 74 },
  { playerName: 'Noah Clowney', position: 'PF', overall: 73 },        // EXACT TEXT
  { playerName: 'Christian Wood', position: 'C', overall: 72 },
],
'Charlotte Hornets': [
  { playerName: 'Anthony Edwards', position: 'SG', overall: 95 },
  { playerName: 'Scottie Barnes', position: 'PF', overall: 86 },
  { playerName: 'Donovan Clingan', position: 'C', overall: 84 },
  { playerName: 'Keegan Murray', position: 'PF', overall: 80 },
  { playerName: 'Buddy Hield', position: 'SG', overall: 80 },
  { playerName: 'Spencer Dinwiddie', position: 'PG', overall: 77 },
  { playerName: 'Luke Kennard', position: 'SF', overall: 76 },
  { playerName: 'Reed Sheppard', position: 'SG', overall: 76 },
  { playerName: 'Kevon Looney', position: 'C', overall: 74 },
  { playerName: 'Grant Williams', position: 'PF', overall: 74 },
  { playerName: 'Jae Crowder', position: 'SF', overall: 74 },
  { playerName: 'Josh Richardson', position: 'PG', overall: 74 },      // EXACT TEXT
  { playerName: 'Andre Jackson Jr.', position: 'SG', overall: 72 },     // EXACT TEXT
  { playerName: 'Bruno Fernando', position: 'C', overall: 70 },
],
'Utah Jazz': [
  { playerName: 'Kevin Durant', position: 'SF', overall: 94 },
  { playerName: 'Jalen Suggs', position: 'PG', overall: 83 },
  { playerName: 'Toumani Camara', position: 'SF', overall: 83 },
  { playerName: 'Naz Reid', position: 'C', overall: 82 },
  { playerName: 'Zach Edey', position: 'C', overall: 80 },
  { playerName: 'Derrick Jones Jr.', position: 'C', overall: 79 },
  { playerName: 'Harrison Barnes', position: 'PF', overall: 79 },
  { playerName: 'C. Carrington', position: 'PG', overall: 77 },   // 2K generated
  { playerName: 'S. James', position: 'SG', overall: 76 },        // 2K generated
  { playerName: 'Day’Ron Sharpe', position: 'C', overall: 75 },
  { playerName: 'Cam Reddish', position: 'SF', overall: 75 },
  { playerName: 'Jericho Sims', position: 'C', overall: 72 },
  { playerName: 'A. Thiero', position: 'PF', overall: 71 },       // 2K generated
  { playerName: 'J.T. Thor', position: 'PF', overall: 71 },
  { playerName: 'Matt Ryan', position: 'SF', overall: 71 },
],
'Sacramento Kings': [
  { playerName: 'Amen Thompson', position: 'PG', overall: 87 },
  { playerName: 'Alex Sarr', position: 'C', overall: 83 },
  { playerName: 'Collin Sexton', position: 'SG', overall: 81 },
  { playerName: 'Matas Buzelis', position: 'SF', overall: 81 },
  { playerName: 'Moses Moody', position: 'SF', overall: 78 },
  { playerName: 'Cole Anthony', position: 'PG', overall: 78 },
  { playerName: 'Jusuf Nurkic', position: 'C', overall: 78 },
  { playerName: 'Peyton Watson', position: 'PF', overall: 77 },
  { playerName: 'Ziaire Williams', position: 'SF', overall: 76 },
  { playerName: 'Bruce Brown', position: 'SG', overall: 76 },
  { playerName: 'Brandon Williams', position: 'PG', overall: 76 },
  { playerName: 'Noa Penda', position: 'SF', overall: 74 },       // shown as N. Penda
  { playerName: 'Tyler Sorber', position: 'C', overall: 72 },     // shown as T. Sorber
  { playerName: 'Dominick Barlow', position: 'PF', overall: 72 },
],
'New York Knicks': [
  { playerName: 'Jayson Tatum', position: 'PF', overall: 94 },
  { playerName: 'Kyrie Irving', position: 'PG', overall: 91 },
  { playerName: 'Zach LaVine', position: 'SG', overall: 86 },
  { playerName: 'Deandre Ayton', position: 'C', overall: 82 },
  { playerName: 'Kelly Oubre Jr.', position: 'SF', overall: 81 },
  { playerName: 'Aaron Wiggins', position: 'SF', overall: 80 },
  { playerName: 'Ryan Rollins', position: 'PG', overall: 79 },
  { playerName: 'Malik Beasley', position: 'SG', overall: 78 },
  { playerName: 'Guerschon Yabusele', position: 'C', overall: 76 },
  { playerName: 'Alec Burks', position: 'SG', overall: 75 },
  { playerName: 'D. Carter', position: 'PG', overall: 75 },      // appears exactly like this in-game
  { playerName: 'Trayce Jackson-Davis', position: 'C', overall: 74 },
  { playerName: 'D. Holmes II', position: 'PF', overall: 72 },
],
'Los Angeles Lakers': [
  { playerName: 'Shai Gilgeous-Alexander', position: 'PG', overall: 95 },
  { playerName: 'Jimmy Butler', position: 'SF', overall: 88 },
  { playerName: 'Coby White', position: 'SG', overall: 83 },
  { playerName: 'Bobby Portis Jr.', position: 'C', overall: 81 },
  { playerName: 'Aaron Nesmith', position: 'SG', overall: 81 },
  { playerName: 'Tobias Harris', position: 'PF', overall: 80 },
  { playerName: 'C.J. McCollum', position: 'PG', overall: 78 },
  { playerName: 'Al Horford', position: 'C', overall: 78 },
  { playerName: 'Colin Gillespie', position: 'PG', overall: 76 },  // C. Gillespie
  { playerName: 'Taurean Prince', position: 'SF', overall: 76 },  // T. Prince
  { playerName: 'Bogdan Bogdanovic', position: 'SF', overall: 76 },
  { playerName: 'Jay Huff', position: 'C', overall: 74 },         // J. Huff
  { playerName: 'Gary Harris', position: 'SG', overall: 73 },
],
'Orlando Magic': [
  { playerName: 'LaMelo Ball', position: 'PG', overall: 88 },
  { playerName: 'Jaren Jackson Jr.', position: 'PF', overall: 88 },
  { playerName: 'Paul George', position: 'SF', overall: 81 },
  { playerName: 'Quentin Grimes', position: 'SG', overall: 78 },
  { playerName: 'Ryan Kalkbrenner', position: 'C', overall: 78 },
  { playerName: 'Ben Simmons', position: 'PG', overall: 78 },
  { playerName: 'Kevin Huerter', position: 'SF', overall: 77 },
  { playerName: 'Dalton Knecht', position: 'SG', overall: 77 },
  { playerName: 'Goga Bitadze', position: 'C', overall: 76 },
  { playerName: 'Saddiq Bey', position: 'SF', overall: 76 },
  { playerName: 'J. Battle', position: 'SF', overall: 75 },
  { playerName: 'Eric Gordon', position: 'SG', overall: 75 },
  { playerName: 'Walter Clayton Jr.', position: 'PG', overall: 73 }, // W. Clayton Jr.
  { playerName: 'Zeke Nnaji', position: 'C', overall: 73 },
  { playerName: 'Jalen Hood-Schifino', position: 'SG', overall: 71 },
],
'Dallas Mavericks': [
  { playerName: 'Anthony Davis', position: 'PF', overall: 93 },
  { playerName: 'Jrue Holiday', position: 'PG', overall: 82 },
  { playerName: 'Dejounte Murray', position: 'PG', overall: 81 },
  { playerName: 'Dereck Lively II', position: 'C', overall: 80 },
  { playerName: 'P.J. Washington', position: 'SF', overall: 79 },
  { playerName: 'Brook Lopez', position: 'C', overall: 79 },
  { playerName: 'Naji Marshall', position: 'SF', overall: 77 },
  { playerName: 'Max Christie', position: 'SG', overall: 76 },
  { playerName: 'Sam Merrill', position: 'SG', overall: 76 },
  { playerName: 'Dante Exum', position: 'SG', overall: 75 },
  { playerName: 'Trendon Watford', position: 'PF', overall: 75 },
  { playerName: 'Kenyon Murray', position: 'SF', overall: 74 },   // K. Murray on screen
  { playerName: 'Oso Ighodaro', position: 'C', overall: 73 },
  { playerName: 'Aaron Holiday', position: 'PG', overall: 73 },
  { playerName: 'Dwight Powell', position: 'C', overall: 73 },
],
'Memphis Grizzlies': [
  { playerName: 'Stephen Curry', position: 'PG', overall: 95 },
  { playerName: 'Julius Randle', position: 'PF', overall: 88 },
  { playerName: 'Ausar Thompson', position: 'SF', overall: 82 },
  { playerName: 'Herb Jones', position: 'SF', overall: 82 },
  { playerName: 'Christian Braun', position: 'SG', overall: 80 },
  { playerName: 'Mitchell Robinson', position: 'C', overall: 80 },
  { playerName: 'Jeremy Sochan', position: 'PF', overall: 79 },
  { playerName: 'Klay Thompson', position: 'SG', overall: 76 },
  { playerName: 'Cam Whitmore', position: 'SF', overall: 76 },
  { playerName: 'Dario Saric', position: 'PF', overall: 75 },
  { playerName: 'Terrence Shannon Jr.', position: 'SG', overall: 74 },
  { playerName: 'Ronald Jackson', position: 'PG', overall: 73 },
  { playerName: 'Kobe Bufkin', position: 'PG', overall: 72 },
  { playerName: 'Tristan Thompson', position: 'C', overall: 70 },
],
'Phoenix Suns': [
  { playerName: 'LeBron James', position: 'SF', overall: 95 },
  { playerName: 'Josh Giddey', position: 'PG', overall: 86 },
  { playerName: 'DeMar DeRozan', position: 'SF', overall: 82 },
  { playerName: 'Russell Westbrook', position: 'PG', overall: 82 },
  { playerName: 'Obi Toppin', position: 'PF', overall: 81 },
  { playerName: 'Mark Williams', position: 'C', overall: 80 },
  { playerName: 'Santi Aldama', position: 'PF', overall: 80 },
  { playerName: 'Grayson Allen', position: 'SG', overall: 79 },
  { playerName: 'Ricky Dunn', position: 'PF', overall: 78 },
  { playerName: 'Jabari Smith', position: 'C', overall: 78 },
  { playerName: 'Jamarius Shead', position: 'PG', overall: 75 },
  { playerName: 'Drew Eubanks', position: 'SF', overall: 75 },
  { playerName: 'Jeff Green', position: 'SF', overall: 74 },
  { playerName: 'Gui Santos', position: 'PF', overall: 73 },
],






};


async function seedDatabase() {
  try {
    await sequelize.authenticate();
    console.log('Database connected successfully.');

    await sequelize.sync({ force: true }); 
    console.log('Database synced.');

    for (const [teamName, players] of Object.entries(teamData)) {
      const team = await NBATeams.create({ teamName });

      for (const player of players) {
        await Player.create({
          playerName: player.playerName,
          position: player.position,
          overall: player.overall,
          teamId: team.id,
        });
      }
    }

    console.log('Seeded NBA teams and players.');
  } catch (err) {
    console.error('Error seeding database:', err);
  } finally {
    await sequelize.close();
  }
}

seedDatabase();
